/** Initial catalog — mirrors legacy static content */
export const productImages = {
  hero: '/images/kitchen_hero_banner.png',
  rangeHood: '/images/range_hood.png',
  gasStove: '/images/gas_stove.png',
  dishDryer: '/images/dish_dryer.png',
  ihStove: '/images/ih_stove.png',
  dishwasher: '/images/dishwasher.png',
  ovenCabinet: '/images/oven_cabinet.png',
}

/** Normalize DB paths to PNG assets in public/images */
export const imagePathMigrations = [
  ['/images/kitchen_hero_banner.svg', productImages.hero],
  ['/images/range_hood.svg', productImages.rangeHood],
  ['/images/gas_stove.svg', productImages.gasStove],
  ['/images/dish_dryer.svg', productImages.dishDryer],
  ['/images/ih_stove.svg', productImages.ihStove],
  ['/images/dishwasher.svg', productImages.dishwasher],
  ['/images/oven_cabinet.svg', productImages.ovenCabinet],
]

export const defaultSite = {
  hero_image: productImages.hero,
  hero_title: '廚房電器系列',
  hero_subtitle: '為您的家庭打造最高品質的廚房美學，體驗極致烹飪樂趣',
  category_intro:
    '櫻花擁有多樣化的廚電商品，其中包含除油煙機、烘碗機、瓦斯爐、洗碗機、IH爐、烤箱等產品，致力於為國人打造最舒適的廚房空間；其中也不乏各項創新技術與國際認證，還有獨家的 SAKURA iCare 服務，永久免費送油網以及永久免費廚房健檢，讓您擁有了櫻花廚電產品後再也無後顧之憂，家中廚房永保如新。',
}

export const defaultCategories = [
  {
    slug: 'hood',
    title: '除油煙機',
    desc: '近吸、歐化與流線系列',
    image_path: productImages.rangeHood,
    anchor: 'recommend-hood',
    icon: '💨',
    sort_order: 0,
    section_title: '除油煙機推薦',
    section_bg: 'var(--light)',
    items: [
      {
        name: '近吸系列',
        tagline: '靠越近 越強勁',
        image_path: productImages.rangeHood,
        spec: '採用近吸式結構，離油煙源更近，超強吸力瞬吸無餘，不漏煙。',
        features: ['智慧感應開關', '超大吸力排風', '易拆洗油網'],
      },
      {
        name: '歐化系列',
        tagline: 'AI風控 全面掌控',
        image_path: productImages.rangeHood,
        spec: '與歐洲設計接軌，流線型外觀與智慧型AI自動偵測調節排風速度。',
        features: ['AI智慧風控', '靜音除味運轉', '全平面不鏽鋼'],
      },
      {
        name: '流線系列',
        tagline: '一體設計 好清潔',
        image_path: productImages.rangeHood,
        spec: '圓弧流線一體成型設計，無接縫好擦拭，為台灣廚房量身打造。',
        features: ['一體成型集煙腔', '雙渦輪強效馬達', '省電LED照明'],
      },
    ],
  },
  {
    slug: 'stove',
    title: '瓦斯爐',
    desc: '檯面爐、台爐與嵌入爐',
    image_path: productImages.gasStove,
    anchor: 'recommend-stove',
    icon: '🔥',
    sort_order: 1,
    section_title: '瓦斯爐推薦',
    section_bg: 'var(--gray-100)',
    items: [
      {
        name: '台爐系列',
        tagline: '經典設計 穩定火力',
        image_path: productImages.gasStove,
        spec: '傳統獨立式放置，高效率節能燃燒器，提供穩定強勁的大火。',
        features: ['防漏清潔盤', '壓電式點火', '銅合金大火力爐頭'],
      },
      {
        name: '檯面爐系列',
        tagline: '平整美觀 好搭配',
        image_path: productImages.gasStove,
        spec: '完美內嵌於流理台，強化玻璃面板美觀大氣，清潔擦拭一氣呵成。',
        features: ['高質感強化玻璃', '雙環高效能烈火', '熄火安全保護裝置'],
      },
      {
        name: '嵌入爐系列',
        tagline: '節省空間 整體性高',
        image_path: productImages.gasStove,
        spec: '嵌入櫥櫃下方，下體拉絲不鏽鋼設計，提供極高性價比與美觀。',
        features: ['抽取式清潔盤', '專利雙環大雙火', '熄火自動切斷安全閥'],
      },
    ],
  },
  {
    slug: 'dryer',
    title: '殺菌烘碗機',
    desc: '落地、吊掛與嵌門板式',
    image_path: productImages.dishDryer,
    anchor: 'recommend-dryer',
    icon: '🍽️',
    sort_order: 2,
    section_title: '殺菌烘碗機推薦',
    section_bg: 'var(--light)',
    items: [
      {
        name: '落地系列',
        tagline: '大容量 抽屜好收納',
        image_path: productImages.dishDryer,
        spec: '雙層大容量抽屜拉門，底部嵌入設計，適合中大型家庭，餐具輕鬆收納。',
        features: ['O3臭氧＋UV雙效殺菌', '滾輪滑軌滑順設計', '大液晶螢幕顯示'],
      },
      {
        name: '吊掛系列',
        tagline: '省空間 觸控式操作',
        image_path: productImages.dishDryer,
        spec: '吊掛於水槽上方，洗完碗盤順手放入，不佔用檯面工作空間空間。',
        features: ['智慧延遲關機', 'PTC陶瓷熱風循環', '防蟲防塵封閉式機體'],
      },
      {
        name: '嵌板門系列',
        tagline: '融入櫃體 廚房一致',
        image_path: productImages.dishDryer,
        spec: '可安裝廚具同色門板，完美隱藏在流理台中，保持空間美感。',
        features: ['高度密合嵌入式', '不鏽鋼內膽設計', '智慧烘乾程式'],
      },
    ],
  },
  {
    slug: 'ih',
    title: 'IH感應爐',
    desc: '智慧觸控、雙口與單口爐',
    image_path: productImages.ihStove,
    anchor: 'recommend-ih',
    icon: '⚡',
    sort_order: 3,
    section_title: 'IH感應爐推薦',
    section_bg: 'var(--gray-100)',
    items: [
      {
        name: '單口系列',
        tagline: '精巧靈活 小宅首選',
        image_path: productImages.ihStove,
        spec: '單口IH電磁加熱，高達90%熱效率，適合單身貴族、套房或輔助爐具。',
        features: ['定時定溫控制', '防乾燒安全偵測', '超薄黑晶玻璃面板'],
      },
      {
        name: '雙口系列',
        tagline: '高功率 火力自由分配',
        image_path: productImages.ihStove,
        spec: '雙口觸控式大功率加熱，智慧型定溫烹調，雙爐同時開工效率翻倍。',
        features: ['PowerBoost快速加熱', '橋接合併加熱區', '定時烹調自動關閉'],
      },
    ],
  },
  {
    slug: 'washer',
    title: '洗碗機',
    desc: '全嵌式與半嵌式洗碗機',
    image_path: productImages.dishwasher,
    anchor: 'recommend-washer',
    icon: '💧',
    sort_order: 4,
    section_title: '洗碗機推薦',
    section_bg: 'var(--light)',
    items: [
      {
        name: '半嵌式系列',
        tagline: '金屬控制面板 精緻美觀',
        image_path: productImages.dishwasher,
        spec: '外部露出金屬顯示面板，運轉狀態一目了然，並能嵌入櫥櫃同色飾板。',
        features: ['高溫銀離子殺菌烘乾', '多重清洗程式', '節能低耗水設計'],
      },
      {
        name: '全嵌式系列',
        tagline: '完全隱形 保持廚房一體感',
        image_path: productImages.dishwasher,
        spec: '控制面板完全隱藏在門頂，關上門後與櫥櫃渾然一體，視覺效果滿分。',
        features: ['投影指示燈技術', '三層中式碗籃彈性調整', '超靜音變頻馬達'],
      },
    ],
  },
  {
    slug: 'oven',
    title: '烤箱與電器收納櫃',
    desc: '嵌入式蒸烤箱與收納櫃',
    image_path: productImages.ovenCabinet,
    anchor: 'recommend-oven',
    icon: '🍞',
    sort_order: 5,
    section_title: '烤箱與電器收納櫃推薦',
    section_bg: 'var(--gray-100)',
    items: [
      {
        name: '烤箱系列',
        tagline: '專業烘烤 智慧控溫',
        image_path: productImages.ovenCabinet,
        spec: '大容量嵌入式專業電烤箱，配備立體熱風循環，讓食材均勻受熱。',
        features: ['3D旋風立體烘烤', '雙層防燙隔熱玻璃門', '內建多種智慧烹調食譜'],
      },
      {
        name: '電器收納櫃系列',
        tagline: '抽拉底板 嵌入式收納',
        image_path: productImages.ovenCabinet,
        spec: '專為電磁爐、電子鍋設計的隱藏收納櫃，配備專利排煙通風防潮散熱功能。',
        features: ['智慧型強排散熱系統', '托盤防滑防傾斜結構', '全彩觸控隱藏開關'],
      },
    ],
  },
]
